// generated by robot. do not edit!

package nodes

import srcPkg "github.com/aws/aws-sdk-go/service/ec2"

// VolumeTypes an array of declarations '^VolumeType.+' extracted from "github.com/aws/aws-sdk-go/service/ec2"
var VolumeTypes = []string{
	srcPkg.VolumeTypeStandard,
	srcPkg.VolumeTypeIo1,
	srcPkg.VolumeTypeGp2,
	srcPkg.VolumeTypeSc1,
	srcPkg.VolumeTypeSt1,
}
